//! # zrame.wl — hand-written Wayland client bindings
//!
//! The thin FFI floor of zrame, in the same spirit as zicro's `gpu_wgpu_bridge_ffi`:
//! explicit `extern` declarations, no `@cImport`. Core `wl_*` interface tables come
//! from libwayland-client; xdg-shell / ext-background-effect / cursor-shape tables are
//! generated by `wayland-scanner private-code` in build.zig and linked in.
//!
//! Every request wrapper is the Zig spelling of the macro the C client headers would
//! have generated: one `wl_proxy_marshal_flags` call with the interface's opcode and
//! signature-ordered arguments. Events arrive through per-interface listener structs
//! (arrays of C function pointers, dispatched by libwayland against the same tables).

const std = @import("std");

// --- libwayland-client core -----------------------------------------------------------

pub const Proxy = opaque {};
pub const Display = opaque {};

pub const Interface = extern struct {
    name: [*:0]const u8,
    version: c_int,
    method_count: c_int,
    methods: ?[*]const Message,
    event_count: c_int,
    events: ?[*]const Message,
};

pub const Message = extern struct {
    name: [*:0]const u8,
    signature: [*:0]const u8,
    types: ?[*]const ?*const Interface,
};

pub const MARSHAL_FLAG_DESTROY: u32 = 1;

pub extern fn wl_display_connect(name: ?[*:0]const u8) ?*Display;
pub extern fn wl_display_disconnect(display: *Display) void;
pub extern fn wl_display_get_fd(display: *Display) c_int;
pub extern fn wl_display_roundtrip(display: *Display) c_int;
pub extern fn wl_display_flush(display: *Display) c_int;
pub extern fn wl_display_dispatch(display: *Display) c_int;
pub extern fn wl_display_dispatch_pending(display: *Display) c_int;
pub extern fn wl_display_prepare_read(display: *Display) c_int;
pub extern fn wl_display_read_events(display: *Display) c_int;
pub extern fn wl_display_cancel_read(display: *Display) void;
pub extern fn wl_display_get_error(display: *Display) c_int;

pub extern fn wl_proxy_marshal_flags(proxy: *Proxy, opcode: u32, interface: ?*const Interface, version: u32, flags: u32, ...) ?*Proxy;
pub extern fn wl_proxy_add_listener(
    proxy: *Proxy,
    implementation: [*]const ?*const fn () callconv(.c) void,
    data: ?*anyopaque,
) c_int;
pub extern fn wl_proxy_get_version(proxy: *Proxy) u32;
pub extern fn wl_proxy_destroy(proxy: *Proxy) void;

// Interface tables. `wl_*` are exported by libwayland-client.so; the rest are compiled
// from wayland-scanner output in build.zig.
pub extern const wl_registry_interface: Interface;
pub extern const wl_callback_interface: Interface;
pub extern const wl_compositor_interface: Interface;
pub extern const wl_surface_interface: Interface;
pub extern const wl_region_interface: Interface;
pub extern const wl_shm_interface: Interface;
pub extern const wl_shm_pool_interface: Interface;
pub extern const wl_buffer_interface: Interface;
pub extern const wl_seat_interface: Interface;
pub extern const wl_pointer_interface: Interface;
pub extern const wl_keyboard_interface: Interface;
pub extern const xdg_wm_base_interface: Interface;
pub extern const xdg_surface_interface: Interface;
pub extern const xdg_toplevel_interface: Interface;
pub extern const ext_background_effect_manager_v1_interface: Interface;
pub extern const ext_background_effect_surface_v1_interface: Interface;
pub extern const wp_cursor_shape_manager_v1_interface: Interface;
pub extern const wp_cursor_shape_device_v1_interface: Interface;
pub extern const wl_subcompositor_interface: Interface;
pub extern const wl_subsurface_interface: Interface;
pub extern const zwp_linux_dmabuf_v1_interface: Interface;
pub extern const zwp_linux_buffer_params_v1_interface: Interface;

/// 24.8 fixed point, the wire format of pointer coordinates.
pub const Fixed = i32;

pub fn fixedToF32(f: Fixed) f32 {
    return @as(f32, @floatFromInt(f)) / 256.0;
}

fn proxy(ptr: anytype) *Proxy {
    return @ptrCast(ptr);
}

fn version(ptr: anytype) u32 {
    return wl_proxy_get_version(@ptrCast(ptr));
}

fn addListener(ptr: anytype, listener: anytype, data: ?*anyopaque) void {
    // `listener` is a pointer to an extern struct of C fn pointers — exactly the
    // implementation array libwayland indexes by opcode.
    _ = wl_proxy_add_listener(@ptrCast(ptr), @ptrCast(@alignCast(listener)), data);
}

// --- wl_display / wl_registry / wl_callback -------------------------------------------

pub const Registry = opaque {
    pub const Listener = extern struct {
        global: *const fn (data: ?*anyopaque, registry: *Registry, name: u32, interface: [*:0]const u8, ver: u32) callconv(.c) void,
        global_remove: *const fn (data: ?*anyopaque, registry: *Registry, name: u32) callconv(.c) void,
    };

    pub fn setListener(self: *Registry, listener: *const Listener, data: ?*anyopaque) void {
        addListener(self, listener, data);
    }

    /// `wl_registry.bind` — signature "usun": the interface name and version travel
    /// with the new_id because the XML leaves the new object's type open.
    pub fn bind(self: *Registry, name: u32, interface: *const Interface, ver: u32) ?*Proxy {
        return wl_proxy_marshal_flags(proxy(self), 0, interface, ver, 0, name, interface.name, ver, @as(?*Proxy, null));
    }
};

pub fn displayGetRegistry(display: *Display) *Registry {
    const p = wl_proxy_marshal_flags(@ptrCast(display), 1, &wl_registry_interface, 1, 0, @as(?*Proxy, null));
    return @ptrCast(p.?);
}

pub const Callback = opaque {
    pub const Listener = extern struct {
        done: *const fn (data: ?*anyopaque, callback: *Callback, callback_data: u32) callconv(.c) void,
    };

    pub fn setListener(self: *Callback, listener: *const Listener, data: ?*anyopaque) void {
        addListener(self, listener, data);
    }

    pub fn destroy(self: *Callback) void {
        wl_proxy_destroy(proxy(self));
    }
};

// --- wl_compositor / wl_surface / wl_region -------------------------------------------

pub const Compositor = opaque {
    pub fn createSurface(self: *Compositor) *Surface {
        const p = wl_proxy_marshal_flags(proxy(self), 0, &wl_surface_interface, version(self), 0, @as(?*Proxy, null));
        return @ptrCast(p.?);
    }

    pub fn createRegion(self: *Compositor) *Region {
        const p = wl_proxy_marshal_flags(proxy(self), 1, &wl_region_interface, version(self), 0, @as(?*Proxy, null));
        return @ptrCast(p.?);
    }
};

pub const Surface = opaque {
    pub fn destroy(self: *Surface) void {
        _ = wl_proxy_marshal_flags(proxy(self), 0, null, version(self), MARSHAL_FLAG_DESTROY);
    }

    pub fn attach(self: *Surface, buffer: ?*Buffer, x: i32, y: i32) void {
        _ = wl_proxy_marshal_flags(proxy(self), 1, null, version(self), 0, @as(?*Proxy, @ptrCast(buffer)), x, y);
    }

    pub fn frame(self: *Surface) *Callback {
        const p = wl_proxy_marshal_flags(proxy(self), 3, &wl_callback_interface, version(self), 0, @as(?*Proxy, null));
        return @ptrCast(p.?);
    }

    pub fn setOpaqueRegion(self: *Surface, region: ?*Region) void {
        _ = wl_proxy_marshal_flags(proxy(self), 4, null, version(self), 0, @as(?*Proxy, @ptrCast(region)));
    }

    pub fn setInputRegion(self: *Surface, region: ?*Region) void {
        _ = wl_proxy_marshal_flags(proxy(self), 5, null, version(self), 0, @as(?*Proxy, @ptrCast(region)));
    }

    pub fn commit(self: *Surface) void {
        _ = wl_proxy_marshal_flags(proxy(self), 6, null, version(self), 0);
    }

    pub fn damageBuffer(self: *Surface, x: i32, y: i32, w: i32, h: i32) void {
        _ = wl_proxy_marshal_flags(proxy(self), 9, null, version(self), 0, x, y, w, h);
    }
};

pub const Region = opaque {
    pub fn destroy(self: *Region) void {
        _ = wl_proxy_marshal_flags(proxy(self), 0, null, version(self), MARSHAL_FLAG_DESTROY);
    }

    pub fn add(self: *Region, x: i32, y: i32, w: i32, h: i32) void {
        _ = wl_proxy_marshal_flags(proxy(self), 1, null, version(self), 0, x, y, w, h);
    }
};

// --- wl_shm / wl_shm_pool / wl_buffer --------------------------------------------------

pub const SHM_FORMAT_ARGB8888: u32 = 0;

pub const Shm = opaque {
    pub fn createPool(self: *Shm, fd: c_int, size: i32) *ShmPool {
        const p = wl_proxy_marshal_flags(proxy(self), 0, &wl_shm_pool_interface, version(self), 0, @as(?*Proxy, null), fd, size);
        return @ptrCast(p.?);
    }
};

pub const ShmPool = opaque {
    pub fn createBuffer(self: *ShmPool, offset: i32, w: i32, h: i32, stride: i32, format: u32) *Buffer {
        const p = wl_proxy_marshal_flags(proxy(self), 0, &wl_buffer_interface, version(self), 0, @as(?*Proxy, null), offset, w, h, stride, format);
        return @ptrCast(p.?);
    }

    pub fn destroy(self: *ShmPool) void {
        _ = wl_proxy_marshal_flags(proxy(self), 1, null, version(self), MARSHAL_FLAG_DESTROY);
    }
};

pub const Buffer = opaque {
    pub const Listener = extern struct {
        release: *const fn (data: ?*anyopaque, buffer: *Buffer) callconv(.c) void,
    };

    pub fn setListener(self: *Buffer, listener: *const Listener, data: ?*anyopaque) void {
        addListener(self, listener, data);
    }

    pub fn destroy(self: *Buffer) void {
        _ = wl_proxy_marshal_flags(proxy(self), 0, null, version(self), MARSHAL_FLAG_DESTROY);
    }
};

// --- wl_subcompositor / wl_subsurface ----------------------------------------------------

pub const Subcompositor = opaque {
    pub fn getSubsurface(self: *Subcompositor, surface: *Surface, parent: *Surface) *Subsurface {
        const p = wl_proxy_marshal_flags(proxy(self), 1, &wl_subsurface_interface, version(self), 0, @as(?*Proxy, null), @as(*Proxy, @ptrCast(surface)), @as(*Proxy, @ptrCast(parent)));
        return @ptrCast(p.?);
    }
};

pub const Subsurface = opaque {
    pub fn destroy(self: *Subsurface) void {
        _ = wl_proxy_marshal_flags(proxy(self), 0, null, version(self), MARSHAL_FLAG_DESTROY);
    }

    pub fn setPosition(self: *Subsurface, x: i32, y: i32) void {
        _ = wl_proxy_marshal_flags(proxy(self), 1, null, version(self), 0, x, y);
    }

    /// Desync: the video subsurface commits on its own cadence, independent of
    /// the parent's (rare) chrome redraws.
    pub fn setDesync(self: *Subsurface) void {
        _ = wl_proxy_marshal_flags(proxy(self), 5, null, version(self), 0);
    }
};

// --- zwp_linux_dmabuf_v1 ------------------------------------------------------------------

pub const LinuxDmabuf = opaque {
    pub fn createParams(self: *LinuxDmabuf) *BufferParams {
        const p = wl_proxy_marshal_flags(proxy(self), 1, &zwp_linux_buffer_params_v1_interface, version(self), 0, @as(?*Proxy, null));
        return @ptrCast(p.?);
    }
};

pub const BufferParams = opaque {
    pub fn destroy(self: *BufferParams) void {
        _ = wl_proxy_marshal_flags(proxy(self), 0, null, version(self), MARSHAL_FLAG_DESTROY);
    }

    pub fn add(self: *BufferParams, fd: c_int, plane: u32, offset: u32, stride: u32, modifier: u64) void {
        _ = wl_proxy_marshal_flags(proxy(self), 1, null, version(self), 0, fd, plane, offset, stride, @as(u32, @intCast(modifier >> 32)), @as(u32, @truncate(modifier)));
    }

    /// `create_immed` (v2+): synchronous buffer creation — an invalid dmabuf is
    /// a protocol error instead of an event, which is fine: our fds come from
    /// a Vulkan export we already validated.
    pub fn createImmed(self: *BufferParams, w: i32, h: i32, format: u32, flags: u32) *Buffer {
        const p = wl_proxy_marshal_flags(proxy(self), 3, &wl_buffer_interface, version(self), 0, @as(?*Proxy, null), w, h, format, flags);
        return @ptrCast(p.?);
    }
};

// --- wl_seat / wl_pointer ---------------------------------------------------------------

pub const SEAT_CAPABILITY_POINTER: u32 = 1;
pub const SEAT_CAPABILITY_KEYBOARD: u32 = 2;
pub const BTN_LEFT: u32 = 0x110;
pub const BTN_RIGHT: u32 = 0x111;
pub const BTN_MIDDLE: u32 = 0x112;
pub const POINTER_BUTTON_STATE_PRESSED: u32 = 1;

/// wl_pointer axis: 0 = vertical, 1 = horizontal.
pub const AXIS_VERTICAL_SCROLL: u32 = 0;
pub const AXIS_HORIZONTAL_SCROLL: u32 = 1;

/// xdg_toplevel.resize_edge bitmask (for interactive resize).
pub const RESIZE_EDGE_NONE: u32 = 0;
pub const RESIZE_EDGE_TOP: u32 = 1;
pub const RESIZE_EDGE_BOTTOM: u32 = 2;
pub const RESIZE_EDGE_LEFT: u32 = 4;
pub const RESIZE_EDGE_TOP_LEFT: u32 = 5;
pub const RESIZE_EDGE_BOTTOM_LEFT: u32 = 6;
pub const RESIZE_EDGE_RIGHT: u32 = 8;
pub const RESIZE_EDGE_TOP_RIGHT: u32 = 9;
pub const RESIZE_EDGE_BOTTOM_RIGHT: u32 = 10;

/// xdg_toplevel.state
pub const STATE_MAXIMIZED: u32 = 1;
pub const STATE_FULLSCREEN: u32 = 2;
pub const STATE_RESIZING: u32 = 3;
pub const STATE_ACTIVATED: u32 = 4;
pub const KEY_ESC: u32 = 1; // linux evdev keycodes
pub const KEY_SPACE: u32 = 57;
pub const KEYBOARD_KEY_STATE_PRESSED: u32 = 1;

pub const Seat = opaque {
    pub const Listener = extern struct {
        capabilities: *const fn (data: ?*anyopaque, seat: *Seat, capabilities: u32) callconv(.c) void,
        name: *const fn (data: ?*anyopaque, seat: *Seat, name: [*:0]const u8) callconv(.c) void,
    };

    pub fn setListener(self: *Seat, listener: *const Listener, data: ?*anyopaque) void {
        addListener(self, listener, data);
    }

    pub fn getPointer(self: *Seat) *Pointer {
        const p = wl_proxy_marshal_flags(proxy(self), 0, &wl_pointer_interface, version(self), 0, @as(?*Proxy, null));
        return @ptrCast(p.?);
    }

    pub fn getKeyboard(self: *Seat) *Keyboard {
        const p = wl_proxy_marshal_flags(proxy(self), 1, &wl_keyboard_interface, version(self), 0, @as(?*Proxy, null));
        return @ptrCast(p.?);
    }
};

pub const Pointer = opaque {
    /// The full wl_pointer event set; entries past the bound version are never invoked.
    pub const Listener = extern struct {
        enter: *const fn (data: ?*anyopaque, pointer: *Pointer, serial: u32, surface: ?*Surface, sx: Fixed, sy: Fixed) callconv(.c) void,
        leave: *const fn (data: ?*anyopaque, pointer: *Pointer, serial: u32, surface: ?*Surface) callconv(.c) void,
        motion: *const fn (data: ?*anyopaque, pointer: *Pointer, time: u32, sx: Fixed, sy: Fixed) callconv(.c) void,
        button: *const fn (data: ?*anyopaque, pointer: *Pointer, serial: u32, time: u32, button: u32, state: u32) callconv(.c) void,
        axis: *const fn (data: ?*anyopaque, pointer: *Pointer, time: u32, axis: u32, value: Fixed) callconv(.c) void,
        frame: *const fn (data: ?*anyopaque, pointer: *Pointer) callconv(.c) void,
        axis_source: *const fn (data: ?*anyopaque, pointer: *Pointer, axis_source: u32) callconv(.c) void,
        axis_stop: *const fn (data: ?*anyopaque, pointer: *Pointer, time: u32, axis: u32) callconv(.c) void,
        axis_discrete: *const fn (data: ?*anyopaque, pointer: *Pointer, axis: u32, discrete: i32) callconv(.c) void,
        axis_value120: *const fn (data: ?*anyopaque, pointer: *Pointer, axis: u32, value120: i32) callconv(.c) void,
        axis_relative_direction: *const fn (data: ?*anyopaque, pointer: *Pointer, axis: u32, direction: u32) callconv(.c) void,
    };

    pub fn setListener(self: *Pointer, listener: *const Listener, data: ?*anyopaque) void {
        addListener(self, listener, data);
    }
};

pub const Keyboard = opaque {
    pub const Listener = extern struct {
        /// Carries an mmap-able fd the listener must close (we read keys as raw evdev
        /// codes, so the xkb keymap itself goes unused).
        keymap: *const fn (data: ?*anyopaque, keyboard: *Keyboard, format: u32, fd: i32, size: u32) callconv(.c) void,
        enter: *const fn (data: ?*anyopaque, keyboard: *Keyboard, serial: u32, surface: ?*Surface, keys: ?*anyopaque) callconv(.c) void,
        leave: *const fn (data: ?*anyopaque, keyboard: *Keyboard, serial: u32, surface: ?*Surface) callconv(.c) void,
        key: *const fn (data: ?*anyopaque, keyboard: *Keyboard, serial: u32, time: u32, key: u32, state: u32) callconv(.c) void,
        modifiers: *const fn (data: ?*anyopaque, keyboard: *Keyboard, serial: u32, depressed: u32, latched: u32, locked: u32, group: u32) callconv(.c) void,
        repeat_info: *const fn (data: ?*anyopaque, keyboard: *Keyboard, rate: i32, delay: i32) callconv(.c) void,
    };

    pub fn setListener(self: *Keyboard, listener: *const Listener, data: ?*anyopaque) void {
        addListener(self, listener, data);
    }
};

// --- xdg-shell ---------------------------------------------------------------------------

pub const XdgWmBase = opaque {
    pub const Listener = extern struct {
        ping: *const fn (data: ?*anyopaque, wm_base: *XdgWmBase, serial: u32) callconv(.c) void,
    };

    pub fn setListener(self: *XdgWmBase, listener: *const Listener, data: ?*anyopaque) void {
        addListener(self, listener, data);
    }

    pub fn getXdgSurface(self: *XdgWmBase, surface: *Surface) *XdgSurface {
        const p = wl_proxy_marshal_flags(proxy(self), 2, &xdg_surface_interface, version(self), 0, @as(?*Proxy, null), @as(*Proxy, @ptrCast(surface)));
        return @ptrCast(p.?);
    }

    pub fn pong(self: *XdgWmBase, serial: u32) void {
        _ = wl_proxy_marshal_flags(proxy(self), 3, null, version(self), 0, serial);
    }
};

pub const XdgSurface = opaque {
    pub const Listener = extern struct {
        configure: *const fn (data: ?*anyopaque, xdg_surface: *XdgSurface, serial: u32) callconv(.c) void,
    };

    pub fn setListener(self: *XdgSurface, listener: *const Listener, data: ?*anyopaque) void {
        addListener(self, listener, data);
    }

    pub fn getToplevel(self: *XdgSurface) *XdgToplevel {
        const p = wl_proxy_marshal_flags(proxy(self), 1, &xdg_toplevel_interface, version(self), 0, @as(?*Proxy, null));
        return @ptrCast(p.?);
    }

    pub fn setWindowGeometry(self: *XdgSurface, x: i32, y: i32, w: i32, h: i32) void {
        _ = wl_proxy_marshal_flags(proxy(self), 3, null, version(self), 0, x, y, w, h);
    }

    pub fn ackConfigure(self: *XdgSurface, serial: u32) void {
        _ = wl_proxy_marshal_flags(proxy(self), 4, null, version(self), 0, serial);
    }
};

pub const XdgToplevel = opaque {
    pub const Listener = extern struct {
        configure: *const fn (data: ?*anyopaque, toplevel: *XdgToplevel, width: i32, height: i32, states: ?*anyopaque) callconv(.c) void,
        close: *const fn (data: ?*anyopaque, toplevel: *XdgToplevel) callconv(.c) void,
        configure_bounds: *const fn (data: ?*anyopaque, toplevel: *XdgToplevel, width: i32, height: i32) callconv(.c) void,
        wm_capabilities: *const fn (data: ?*anyopaque, toplevel: *XdgToplevel, capabilities: ?*anyopaque) callconv(.c) void,
    };

    pub fn setListener(self: *XdgToplevel, listener: *const Listener, data: ?*anyopaque) void {
        addListener(self, listener, data);
    }

    pub fn setTitle(self: *XdgToplevel, title: [*:0]const u8) void {
        _ = wl_proxy_marshal_flags(proxy(self), 2, null, version(self), 0, title);
    }

    pub fn setAppId(self: *XdgToplevel, app_id: [*:0]const u8) void {
        _ = wl_proxy_marshal_flags(proxy(self), 3, null, version(self), 0, app_id);
    }

    pub fn move(self: *XdgToplevel, seat: *Seat, serial: u32) void {
        _ = wl_proxy_marshal_flags(proxy(self), 5, null, version(self), 0, @as(*Proxy, @ptrCast(seat)), serial);
    }

    /// resize (opcode 6): interactive resize toward `edges` (a `RESIZE_EDGE_*` bitmask).
    pub fn resize(self: *XdgToplevel, seat: *Seat, serial: u32, edges: u32) void {
        _ = wl_proxy_marshal_flags(proxy(self), 6, null, version(self), 0, @as(*Proxy, @ptrCast(seat)), serial, edges);
    }

    /// show_window_menu (opcode 4): ask the compositor for its own window menu at (x,y),
    /// panel-relative. `serial` must come from a recent input event.
    pub fn showWindowMenu(self: *XdgToplevel, seat: *Seat, serial: u32, x: i32, y: i32) void {
        _ = wl_proxy_marshal_flags(proxy(self), 4, null, version(self), 0, @as(*Proxy, @ptrCast(seat)), serial, x, y);
    }

    pub fn setMinSize(self: *XdgToplevel, w: i32, h: i32) void {
        _ = wl_proxy_marshal_flags(proxy(self), 8, null, version(self), 0, w, h);
    }

    /// set_maximized (opcode 9): the compositor answers with a configure carrying the
    /// maximized state and the tiled size.
    pub fn setMaximized(self: *XdgToplevel) void {
        _ = wl_proxy_marshal_flags(proxy(self), 9, null, version(self), 0);
    }

    /// unset_maximized (opcode 10).
    pub fn unsetMaximized(self: *XdgToplevel) void {
        _ = wl_proxy_marshal_flags(proxy(self), 10, null, version(self), 0);
    }

    /// set_minimized (opcode 13): request iconify. There is no matching state in configure
    /// — minimized windows just stop being drawn — so nothing to restore on our side.
    pub fn setMinimized(self: *XdgToplevel) void {
        _ = wl_proxy_marshal_flags(proxy(self), 13, null, version(self), 0);
    }

    /// set_fullscreen (opcode 11): output null = il compositore sceglie l'output.
    pub fn setFullscreen(self: *XdgToplevel) void {
        _ = wl_proxy_marshal_flags(proxy(self), 11, null, version(self), 0, @as(?*Proxy, null));
    }

    /// unset_fullscreen (opcode 12): torna allo stato a finestra.
    pub fn unsetFullscreen(self: *XdgToplevel) void {
        _ = wl_proxy_marshal_flags(proxy(self), 12, null, version(self), 0);
    }
};

// --- ext-background-effect-v1 (compositor blur) -------------------------------------------

pub const BackgroundEffectManager = opaque {
    pub const Listener = extern struct {
        capabilities: *const fn (data: ?*anyopaque, manager: *BackgroundEffectManager, flags: u32) callconv(.c) void,
    };

    pub const CAPABILITY_BLUR: u32 = 1;

    pub fn setListener(self: *BackgroundEffectManager, listener: *const Listener, data: ?*anyopaque) void {
        addListener(self, listener, data);
    }

    pub fn getBackgroundEffect(self: *BackgroundEffectManager, surface: *Surface) *BackgroundEffectSurface {
        const p = wl_proxy_marshal_flags(proxy(self), 1, &ext_background_effect_surface_v1_interface, version(self), 0, @as(?*Proxy, null), @as(*Proxy, @ptrCast(surface)));
        return @ptrCast(p.?);
    }
};

pub const BackgroundEffectSurface = opaque {
    pub fn setBlurRegion(self: *BackgroundEffectSurface, region: ?*Region) void {
        _ = wl_proxy_marshal_flags(proxy(self), 1, null, version(self), 0, @as(?*Proxy, @ptrCast(region)));
    }
};

// --- cursor-shape-v1 ------------------------------------------------------------------------

pub const CursorShapeManager = opaque {
    pub fn getPointer(self: *CursorShapeManager, pointer: *Pointer) *CursorShapeDevice {
        const p = wl_proxy_marshal_flags(proxy(self), 1, &wp_cursor_shape_device_v1_interface, version(self), 0, @as(?*Proxy, null), @as(*Proxy, @ptrCast(pointer)));
        return @ptrCast(p.?);
    }
};

pub const CursorShapeDevice = opaque {
    pub const SHAPE_DEFAULT: u32 = 1;
    pub const SHAPE_POINTER: u32 = 4;
    pub const SHAPE_MOVE: u32 = 13;
    pub const SHAPE_EW_RESIZE: u32 = 26;
    pub const SHAPE_NS_RESIZE: u32 = 27;
    pub const SHAPE_NESW_RESIZE: u32 = 28;
    pub const SHAPE_NWSE_RESIZE: u32 = 29;

    pub fn setShape(self: *CursorShapeDevice, serial: u32, shape: u32) void {
        _ = wl_proxy_marshal_flags(proxy(self), 1, null, version(self), 0, serial, shape);
    }
};
